import React from 'react';

const PrintableReceipts = React.forwardRef(({ receipts, user }, ref) => {
  return (
    <div ref={ref} className="p-8 font-sans">
      <h1 className="text-2xl font-bold mb-4">E-VoteKE Voter Receipts</h1>
      <p className="mb-6">
        This document contains a record of your votes cast on E-VoteKE.
      </p>

      <div className="mb-8 border p-4 rounded-lg">
        <h2 className="text-xl font-semibold mb-2">Voter Information</h2>
        <p><strong>Name:</strong> {user.firstName} {user.lastName}</p>
        <p><strong>Voter ID:</strong> {user.voterId}</p>
        <p><strong>Constituency:</strong> {user.constituency}, {user.county} County</p>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-semibold mb-2">Vote Records</h2>
        {receipts.length === 0 ? (
          <p>No votes have been cast yet.</p>
        ) : (
          receipts.map((receipt) => (
            <div key={receipt.id} className="border-b pb-4">
              <p>
                <strong>Election:</strong> {receipt.electionTitle}
              </p>
              <p>
                <strong>Candidate:</strong> {receipt.candidateName}
              </p>
              <p>
                <strong>Date & Time:</strong> {new Date(receipt.timestamp).toLocaleString()}
              </p>
              <p>
                <strong>Vote Hash:</strong> <span className="text-xs font-mono">{receipt.voteHash}</span>
              </p>
            </div>
          ))
        )}
      </div>
      <p className="mt-8 text-sm text-gray-500">
        Generated by E-VoteKE on {new Date().toLocaleDateString()}
      </p>
    </div>
  );
});

export default PrintableReceipts;